name: Build and Deploy SAM App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # needed for OIDC
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install all required
        run: |
            pip install -r requirements.txt

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Build SAM app
        run: |
          sam build

      - name: Deploy SAM app
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --resolve-s3 \
            --stack-name helloer \
            --capabilities CAPABILITY_IAM \
            --region ${{ secrets.AWS_DEFAULT_REGION }}
